var hierarchy =
[
    [ "UBX::checksum_t", "struct_u_b_x_1_1checksum__t.html", null ],
    [ "std::exception", null, [
      [ "GNSS::EndOfFile", "class_g_n_s_s_1_1_end_of_file.html", null ],
      [ "GNSS::InsufficientData", "class_g_n_s_s_1_1_insufficient_data.html", null ],
      [ "GNSS::InvalidMessage", "class_g_n_s_s_1_1_invalid_message.html", null ],
      [ "GNSS::NotSendable", "class_g_n_s_s_1_1_not_sendable.html", null ],
      [ "NMEA0183::ChecksumMismatch", "class_n_m_e_a0183_1_1_checksum_mismatch.html", null ],
      [ "NMEA0183::InvalidSentence", "class_n_m_e_a0183_1_1_invalid_sentence.html", null ],
      [ "NMEA0183::UnknownSentenceType", "class_n_m_e_a0183_1_1_unknown_sentence_type.html", null ],
      [ "SkyTraqBin::ChecksumMismatch", "class_sky_traq_bin_1_1_checksum_mismatch.html", null ],
      [ "SkyTraqBin::UnknownMessageID", "class_sky_traq_bin_1_1_unknown_message_i_d.html", null ],
      [ "UBX::ChecksumMismatch", "class_u_b_x_1_1_checksum_mismatch.html", null ],
      [ "UBX::UnknownMessageID", "class_u_b_x_1_1_unknown_message_i_d.html", null ]
    ] ],
    [ "UBX::Cfg::GNSS_config", "struct_u_b_x_1_1_cfg_1_1_g_n_s_s__config.html", null ],
    [ "GNSS::Interface", "class_g_n_s_s_1_1_interface.html", null ],
    [ "GNSS::Listener", "class_g_n_s_s_1_1_listener.html", [
      [ "GNSS::Listener_SkyTraq", "class_g_n_s_s_1_1_listener___sky_traq.html", null ],
      [ "GNSS::Listener_Ublox", "class_g_n_s_s_1_1_listener___ublox.html", null ]
    ] ],
    [ "GNSS::Message", "class_g_n_s_s_1_1_message.html", [
      [ "NMEA0183::Sentence", "class_n_m_e_a0183_1_1_sentence.html", [
        [ "NMEA0183::GGA", "class_n_m_e_a0183_1_1_g_g_a.html", null ],
        [ "NMEA0183::GLL", "class_n_m_e_a0183_1_1_g_l_l.html", null ],
        [ "NMEA0183::GSA", "class_n_m_e_a0183_1_1_g_s_a.html", null ],
        [ "NMEA0183::GSV", "class_n_m_e_a0183_1_1_g_s_v.html", null ],
        [ "NMEA0183::RMC", "class_n_m_e_a0183_1_1_r_m_c.html", null ],
        [ "NMEA0183::STI_PPS", "class_n_m_e_a0183_1_1_s_t_i___p_p_s.html", null ],
        [ "NMEA0183::STI_sensors", "class_n_m_e_a0183_1_1_s_t_i__sensors.html", null ],
        [ "NMEA0183::VTG", "class_n_m_e_a0183_1_1_v_t_g.html", null ],
        [ "NMEA0183::ZDA", "class_n_m_e_a0183_1_1_z_d_a.html", null ]
      ] ],
      [ "SkyTraqBin::Message", "class_sky_traq_bin_1_1_message.html", [
        [ "SkyTraqBin::Input_message", "class_sky_traq_bin_1_1_input__message.html", [
          [ "SkyTraqBin::Clear_log", "class_sky_traq_bin_1_1_clear__log.html", null ],
          [ "SkyTraqBin::Config_1PPS_cable_delay", "class_sky_traq_bin_1_1_config__1_p_p_s__cable__delay.html", null ],
          [ "SkyTraqBin::Config_1PPS_timing", "class_sky_traq_bin_1_1_config__1_p_p_s__timing.html", null ],
          [ "SkyTraqBin::Config_bin_measurement_data_output", "class_sky_traq_bin_1_1_config__bin__measurement__data__output.html", null ],
          [ "SkyTraqBin::Config_bin_measurement_output_rates", "class_sky_traq_bin_1_1_config__bin__measurement__output__rates.html", null ],
          [ "SkyTraqBin::Config_datum", "class_sky_traq_bin_1_1_config__datum.html", null ],
          [ "SkyTraqBin::Config_DOP_mask", "class_sky_traq_bin_1_1_config___d_o_p__mask.html", null ],
          [ "SkyTraqBin::Config_elevation_CNR_mask", "class_sky_traq_bin_1_1_config__elevation___c_n_r__mask.html", null ],
          [ "SkyTraqBin::Config_logging", "class_sky_traq_bin_1_1_config__logging.html", null ],
          [ "SkyTraqBin::Config_msg_type", "class_sky_traq_bin_1_1_config__msg__type.html", null ],
          [ "SkyTraqBin::Config_nav_data_msg_interval", "class_sky_traq_bin_1_1_config__nav__data__msg__interval.html", null ],
          [ "SkyTraqBin::Config_NMEA_msg", "class_sky_traq_bin_1_1_config___n_m_e_a__msg.html", null ],
          [ "SkyTraqBin::Config_NMEA_talker_ID", "class_sky_traq_bin_1_1_config___n_m_e_a__talker___i_d.html", null ],
          [ "SkyTraqBin::Config_pos_pinning", "class_sky_traq_bin_1_1_config__pos__pinning.html", null ],
          [ "SkyTraqBin::Config_pos_pinning_params", "class_sky_traq_bin_1_1_config__pos__pinning__params.html", null ],
          [ "SkyTraqBin::Config_serial_port", "class_sky_traq_bin_1_1_config__serial__port.html", null ],
          [ "SkyTraqBin::Config_sys_pos_rate", "class_sky_traq_bin_1_1_config__sys__pos__rate.html", null ],
          [ "SkyTraqBin::Config_sys_power_mode", "class_sky_traq_bin_1_1_config__sys__power__mode.html", null ],
          [ "SkyTraqBin::Get_almanac", "class_sky_traq_bin_1_1_get__almanac.html", null ],
          [ "SkyTraqBin::Get_Glonass_ephemeris", "class_sky_traq_bin_1_1_get___glonass__ephemeris.html", null ],
          [ "SkyTraqBin::Get_GPS_ephemeris", "class_sky_traq_bin_1_1_get___g_p_s__ephemeris.html", null ],
          [ "SkyTraqBin::Input_message_with_subid", "class_sky_traq_bin_1_1_input__message__with__subid.html", [
            [ "SkyTraqBin::Config_1PPS_freq_output", "class_sky_traq_bin_1_1_config__1_p_p_s__freq__output.html", null ],
            [ "SkyTraqBin::Config_1PPS_pulse_width", "class_sky_traq_bin_1_1_config__1_p_p_s__pulse__width.html", null ],
            [ "SkyTraqBin::Config_constellation_type", "class_sky_traq_bin_1_1_config__constellation__type.html", null ],
            [ "SkyTraqBin::Config_extended_NMEA_msg_interval", "class_sky_traq_bin_1_1_config__extended___n_m_e_a__msg__interval.html", null ],
            [ "SkyTraqBin::Config_GNSS_datum_index", "class_sky_traq_bin_1_1_config___g_n_s_s__datum__index.html", null ],
            [ "SkyTraqBin::Config_GNSS_nav_mode", "class_sky_traq_bin_1_1_config___g_n_s_s__nav__mode.html", null ],
            [ "SkyTraqBin::Config_GPS_param_search_engine_num", "class_sky_traq_bin_1_1_config___g_p_s__param__search__engine__num.html", null ],
            [ "SkyTraqBin::Config_interference_detection", "class_sky_traq_bin_1_1_config__interference__detection.html", null ],
            [ "SkyTraqBin::Config_leap_seconds", "class_sky_traq_bin_1_1_config__leap__seconds.html", null ],
            [ "SkyTraqBin::Config_QZSS", "class_sky_traq_bin_1_1_config___q_z_s_s.html", null ],
            [ "SkyTraqBin::Config_SAEE", "class_sky_traq_bin_1_1_config___s_a_e_e.html", null ],
            [ "SkyTraqBin::Config_SBAS", "class_sky_traq_bin_1_1_config___s_b_a_s.html", null ],
            [ "SkyTraqBin::Q_1PPS_freq_output", "class_sky_traq_bin_1_1_q__1_p_p_s__freq__output.html", null ],
            [ "SkyTraqBin::Q_1PPS_pulse_width", "class_sky_traq_bin_1_1_q__1_p_p_s__pulse__width.html", null ],
            [ "SkyTraqBin::Q_constellation_type", "class_sky_traq_bin_1_1_q__constellation__type.html", null ],
            [ "SkyTraqBin::Q_extended_NMEA_msg_interval", "class_sky_traq_bin_1_1_q__extended___n_m_e_a__msg__interval.html", null ],
            [ "SkyTraqBin::Q_GNSS_boot_status", "class_sky_traq_bin_1_1_q___g_n_s_s__boot__status.html", null ],
            [ "SkyTraqBin::Q_GNSS_datum_index", "class_sky_traq_bin_1_1_q___g_n_s_s__datum__index.html", null ],
            [ "SkyTraqBin::Q_GNSS_nav_mode", "class_sky_traq_bin_1_1_q___g_n_s_s__nav__mode.html", null ],
            [ "SkyTraqBin::Q_GPS_param_search_engine_num", "class_sky_traq_bin_1_1_q___g_p_s__param__search__engine__num.html", null ],
            [ "SkyTraqBin::Q_GPS_time", "class_sky_traq_bin_1_1_q___g_p_s__time.html", null ],
            [ "SkyTraqBin::Q_interference_detection_status", "class_sky_traq_bin_1_1_q__interference__detection__status.html", null ],
            [ "SkyTraqBin::Q_QZSS_status", "class_sky_traq_bin_1_1_q___q_z_s_s__status.html", null ],
            [ "SkyTraqBin::Q_SAEE_status", "class_sky_traq_bin_1_1_q___s_a_e_e__status.html", null ],
            [ "SkyTraqBin::Q_SBAS_status", "class_sky_traq_bin_1_1_q___s_b_a_s__status.html", null ]
          ] ],
          [ "SkyTraqBin::Q_1PPS_cable_delay", "class_sky_traq_bin_1_1_q__1_p_p_s__cable__delay.html", null ],
          [ "SkyTraqBin::Q_1PPS_timing", "class_sky_traq_bin_1_1_q__1_p_p_s__timing.html", null ],
          [ "SkyTraqBin::Q_bin_messurement_data_output_status", "class_sky_traq_bin_1_1_q__bin__messurement__data__output__status.html", null ],
          [ "SkyTraqBin::Q_datum", "class_sky_traq_bin_1_1_q__datum.html", null ],
          [ "SkyTraqBin::Q_DOP_mask", "class_sky_traq_bin_1_1_q___d_o_p__mask.html", null ],
          [ "SkyTraqBin::Q_elevation_CNR_mask", "class_sky_traq_bin_1_1_q__elevation___c_n_r__mask.html", null ],
          [ "SkyTraqBin::Q_log_status", "class_sky_traq_bin_1_1_q__log__status.html", null ],
          [ "SkyTraqBin::Q_NMEA_talker_ID", "class_sky_traq_bin_1_1_q___n_m_e_a__talker___i_d.html", null ],
          [ "SkyTraqBin::Q_pos_pinning", "class_sky_traq_bin_1_1_q__pos__pinning.html", null ],
          [ "SkyTraqBin::Q_pos_update_rate", "class_sky_traq_bin_1_1_q__pos__update__rate.html", null ],
          [ "SkyTraqBin::Q_power_mode", "class_sky_traq_bin_1_1_q__power__mode.html", null ],
          [ "SkyTraqBin::Q_sw_CRC", "class_sky_traq_bin_1_1_q__sw___c_r_c.html", null ],
          [ "SkyTraqBin::Q_sw_ver", "class_sky_traq_bin_1_1_q__sw__ver.html", null ],
          [ "SkyTraqBin::Read_log", "class_sky_traq_bin_1_1_read__log.html", null ],
          [ "SkyTraqBin::Restart_sys", "class_sky_traq_bin_1_1_restart__sys.html", null ],
          [ "SkyTraqBin::Set_factory_defaults", "class_sky_traq_bin_1_1_set__factory__defaults.html", null ],
          [ "SkyTraqBin::Set_Glonass_ephemeris", "class_sky_traq_bin_1_1_set___glonass__ephemeris.html", null ],
          [ "SkyTraqBin::Set_GPS_ephemeris", "class_sky_traq_bin_1_1_set___g_p_s__ephemeris.html", null ],
          [ "SkyTraqBin::Sw_img_download", "class_sky_traq_bin_1_1_sw__img__download.html", null ]
        ] ],
        [ "SkyTraqBin::Output_message", "class_sky_traq_bin_1_1_output__message.html", [
          [ "SkyTraqBin::Ack", "class_sky_traq_bin_1_1_ack.html", null ],
          [ "SkyTraqBin::Beidou2_subframe_data", "class_sky_traq_bin_1_1_beidou2__subframe__data.html", null ],
          [ "SkyTraqBin::Bin_measurement_data_output_status", "class_sky_traq_bin_1_1_bin__measurement__data__output__status.html", null ],
          [ "SkyTraqBin::Glonass_ephemeris_data", "class_sky_traq_bin_1_1_glonass__ephemeris__data.html", null ],
          [ "SkyTraqBin::Glonass_string_data", "class_sky_traq_bin_1_1_glonass__string__data.html", null ],
          [ "SkyTraqBin::GNSS_1PPS_cable_delay", "class_sky_traq_bin_1_1_g_n_s_s__1_p_p_s__cable__delay.html", null ],
          [ "SkyTraqBin::GNSS_1PPS_timing", "class_sky_traq_bin_1_1_g_n_s_s__1_p_p_s__timing.html", null ],
          [ "SkyTraqBin::GNSS_datum", "class_sky_traq_bin_1_1_g_n_s_s__datum.html", null ],
          [ "SkyTraqBin::GNSS_DOP_mask", "class_sky_traq_bin_1_1_g_n_s_s___d_o_p__mask.html", null ],
          [ "SkyTraqBin::GNSS_elevation_CNR_mask", "class_sky_traq_bin_1_1_g_n_s_s__elevation___c_n_r__mask.html", null ],
          [ "SkyTraqBin::GNSS_pos_pinning_status", "class_sky_traq_bin_1_1_g_n_s_s__pos__pinning__status.html", null ],
          [ "SkyTraqBin::GNSS_power_mode_status", "class_sky_traq_bin_1_1_g_n_s_s__power__mode__status.html", null ],
          [ "SkyTraqBin::GPS_almanac_data", "class_sky_traq_bin_1_1_g_p_s__almanac__data.html", null ],
          [ "SkyTraqBin::GPS_ephemeris_data", "class_sky_traq_bin_1_1_g_p_s__ephemeris__data.html", null ],
          [ "SkyTraqBin::GPS_subframe_data", "class_sky_traq_bin_1_1_g_p_s__subframe__data.html", null ],
          [ "SkyTraqBin::Log_status_output", "class_sky_traq_bin_1_1_log__status__output.html", null ],
          [ "SkyTraqBin::Measurement_time", "class_sky_traq_bin_1_1_measurement__time.html", null ],
          [ "SkyTraqBin::Nack", "class_sky_traq_bin_1_1_nack.html", null ],
          [ "SkyTraqBin::Nav_data_msg", "class_sky_traq_bin_1_1_nav__data__msg.html", null ],
          [ "SkyTraqBin::NMEA_talker_ID", "class_sky_traq_bin_1_1_n_m_e_a__talker___i_d.html", null ],
          [ "SkyTraqBin::Output_message_with_subid", "class_sky_traq_bin_1_1_output__message__with__subid.html", [
            [ "SkyTraqBin::GNSS_1PPS_freq_output", "class_sky_traq_bin_1_1_g_n_s_s__1_p_p_s__freq__output.html", null ],
            [ "SkyTraqBin::GNSS_1PPS_pulse_width", "class_sky_traq_bin_1_1_g_n_s_s__1_p_p_s__pulse__width.html", null ],
            [ "SkyTraqBin::GNSS_boot_status", "class_sky_traq_bin_1_1_g_n_s_s__boot__status.html", null ],
            [ "SkyTraqBin::GNSS_constellation_type", "class_sky_traq_bin_1_1_g_n_s_s__constellation__type.html", null ],
            [ "SkyTraqBin::GNSS_datum_index", "class_sky_traq_bin_1_1_g_n_s_s__datum__index.html", null ],
            [ "SkyTraqBin::GNSS_extended_NMEA_msg_interval", "class_sky_traq_bin_1_1_g_n_s_s__extended___n_m_e_a__msg__interval.html", null ],
            [ "SkyTraqBin::GNSS_interference_detection_status", "class_sky_traq_bin_1_1_g_n_s_s__interference__detection__status.html", null ],
            [ "SkyTraqBin::GNSS_nav_mode", "class_sky_traq_bin_1_1_g_n_s_s__nav__mode.html", null ],
            [ "SkyTraqBin::GNSS_QZSS_status", "class_sky_traq_bin_1_1_g_n_s_s___q_z_s_s__status.html", null ],
            [ "SkyTraqBin::GNSS_SAEE_status", "class_sky_traq_bin_1_1_g_n_s_s___s_a_e_e__status.html", null ],
            [ "SkyTraqBin::GNSS_SBAS_status", "class_sky_traq_bin_1_1_g_n_s_s___s_b_a_s__status.html", null ],
            [ "SkyTraqBin::GNSS_time", "class_sky_traq_bin_1_1_g_n_s_s__time.html", null ],
            [ "SkyTraqBin::GPS_param_search_engine_num", "class_sky_traq_bin_1_1_g_p_s__param__search__engine__num.html", null ],
            [ "SkyTraqBin::Sensor_data", "class_sky_traq_bin_1_1_sensor__data.html", null ]
          ] ],
          [ "SkyTraqBin::Pos_update_rate", "class_sky_traq_bin_1_1_pos__update__rate.html", null ],
          [ "SkyTraqBin::Raw_measurements", "class_sky_traq_bin_1_1_raw__measurements.html", null ],
          [ "SkyTraqBin::Rcv_state", "class_sky_traq_bin_1_1_rcv__state.html", null ],
          [ "SkyTraqBin::SV_channel_status", "class_sky_traq_bin_1_1_s_v__channel__status.html", null ],
          [ "SkyTraqBin::Sw_CRC", "class_sky_traq_bin_1_1_sw___c_r_c.html", null ],
          [ "SkyTraqBin::Sw_ver", "class_sky_traq_bin_1_1_sw__ver.html", null ]
        ] ]
      ] ],
      [ "UBX::Message", "class_u_b_x_1_1_message.html", [
        [ "UBX::Input_message", "class_u_b_x_1_1_input__message.html", [
          [ "UBX::Cfg::Q_GNSS", "class_u_b_x_1_1_cfg_1_1_q___g_n_s_s.html", null ],
          [ "UBX::Cfg::Q_msg", "class_u_b_x_1_1_cfg_1_1_q__msg.html", null ],
          [ "UBX::Cfg::Q_prt", "class_u_b_x_1_1_cfg_1_1_q__prt.html", null ],
          [ "UBX::Input_Output_message", "class_u_b_x_1_1_input___output__message.html", [
            [ "UBX::Cfg::GNSS", "class_u_b_x_1_1_cfg_1_1_g_n_s_s.html", null ],
            [ "UBX::Cfg::Msg", "class_u_b_x_1_1_cfg_1_1_msg.html", null ],
            [ "UBX::Cfg::Prt", "class_u_b_x_1_1_cfg_1_1_prt.html", null ]
          ] ]
        ] ],
        [ "UBX::Output_message", "class_u_b_x_1_1_output__message.html", [
          [ "UBX::Ack::Ack", "class_u_b_x_1_1_ack_1_1_ack.html", null ],
          [ "UBX::Ack::Nak", "class_u_b_x_1_1_ack_1_1_nak.html", null ],
          [ "UBX::Input_Output_message", "class_u_b_x_1_1_input___output__message.html", null ]
        ] ]
      ] ]
    ] ],
    [ "SkyTraqBin::PackedVersion", "struct_sky_traq_bin_1_1_packed_version.html", null ],
    [ "GNSS::Parser", "class_g_n_s_s_1_1_parser.html", null ],
    [ "SkyTraqBin::RawMeasurement", "struct_sky_traq_bin_1_1_raw_measurement.html", null ],
    [ "NMEA0183::SatelliteData", "struct_n_m_e_a0183_1_1_satellite_data.html", null ],
    [ "SkyTraqBin::SvStatus", "struct_sky_traq_bin_1_1_sv_status.html", null ],
    [ "SkyTraqBin::with_response", "class_sky_traq_bin_1_1with__response.html", [
      [ "SkyTraqBin::Get_almanac", "class_sky_traq_bin_1_1_get__almanac.html", null ],
      [ "SkyTraqBin::Get_Glonass_ephemeris", "class_sky_traq_bin_1_1_get___glonass__ephemeris.html", null ],
      [ "SkyTraqBin::Get_GPS_ephemeris", "class_sky_traq_bin_1_1_get___g_p_s__ephemeris.html", null ],
      [ "SkyTraqBin::Q_1PPS_cable_delay", "class_sky_traq_bin_1_1_q__1_p_p_s__cable__delay.html", null ],
      [ "SkyTraqBin::Q_1PPS_freq_output", "class_sky_traq_bin_1_1_q__1_p_p_s__freq__output.html", null ],
      [ "SkyTraqBin::Q_1PPS_pulse_width", "class_sky_traq_bin_1_1_q__1_p_p_s__pulse__width.html", null ],
      [ "SkyTraqBin::Q_1PPS_timing", "class_sky_traq_bin_1_1_q__1_p_p_s__timing.html", null ],
      [ "SkyTraqBin::Q_bin_messurement_data_output_status", "class_sky_traq_bin_1_1_q__bin__messurement__data__output__status.html", null ],
      [ "SkyTraqBin::Q_constellation_type", "class_sky_traq_bin_1_1_q__constellation__type.html", null ],
      [ "SkyTraqBin::Q_datum", "class_sky_traq_bin_1_1_q__datum.html", null ],
      [ "SkyTraqBin::Q_DOP_mask", "class_sky_traq_bin_1_1_q___d_o_p__mask.html", null ],
      [ "SkyTraqBin::Q_elevation_CNR_mask", "class_sky_traq_bin_1_1_q__elevation___c_n_r__mask.html", null ],
      [ "SkyTraqBin::Q_extended_NMEA_msg_interval", "class_sky_traq_bin_1_1_q__extended___n_m_e_a__msg__interval.html", null ],
      [ "SkyTraqBin::Q_GNSS_boot_status", "class_sky_traq_bin_1_1_q___g_n_s_s__boot__status.html", null ],
      [ "SkyTraqBin::Q_GNSS_datum_index", "class_sky_traq_bin_1_1_q___g_n_s_s__datum__index.html", null ],
      [ "SkyTraqBin::Q_GNSS_nav_mode", "class_sky_traq_bin_1_1_q___g_n_s_s__nav__mode.html", null ],
      [ "SkyTraqBin::Q_GPS_param_search_engine_num", "class_sky_traq_bin_1_1_q___g_p_s__param__search__engine__num.html", null ],
      [ "SkyTraqBin::Q_GPS_time", "class_sky_traq_bin_1_1_q___g_p_s__time.html", null ],
      [ "SkyTraqBin::Q_interference_detection_status", "class_sky_traq_bin_1_1_q__interference__detection__status.html", null ],
      [ "SkyTraqBin::Q_log_status", "class_sky_traq_bin_1_1_q__log__status.html", null ],
      [ "SkyTraqBin::Q_NMEA_talker_ID", "class_sky_traq_bin_1_1_q___n_m_e_a__talker___i_d.html", null ],
      [ "SkyTraqBin::Q_pos_pinning", "class_sky_traq_bin_1_1_q__pos__pinning.html", null ],
      [ "SkyTraqBin::Q_pos_update_rate", "class_sky_traq_bin_1_1_q__pos__update__rate.html", null ],
      [ "SkyTraqBin::Q_power_mode", "class_sky_traq_bin_1_1_q__power__mode.html", null ],
      [ "SkyTraqBin::Q_QZSS_status", "class_sky_traq_bin_1_1_q___q_z_s_s__status.html", null ],
      [ "SkyTraqBin::Q_SAEE_status", "class_sky_traq_bin_1_1_q___s_a_e_e__status.html", null ],
      [ "SkyTraqBin::Q_SBAS_status", "class_sky_traq_bin_1_1_q___s_b_a_s__status.html", null ],
      [ "SkyTraqBin::Q_sw_CRC", "class_sky_traq_bin_1_1_q__sw___c_r_c.html", null ],
      [ "SkyTraqBin::Q_sw_ver", "class_sky_traq_bin_1_1_q__sw__ver.html", null ]
    ] ],
    [ "SkyTraqBin::with_subid", "class_sky_traq_bin_1_1with__subid.html", [
      [ "SkyTraqBin::Input_message_with_subid", "class_sky_traq_bin_1_1_input__message__with__subid.html", null ],
      [ "SkyTraqBin::Output_message_with_subid", "class_sky_traq_bin_1_1_output__message__with__subid.html", null ]
    ] ]
];